config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_xsettingsd:
    src: config/xsettingsd
    dst: ~/.config/xsettingsd
  d_fuzzel:
    src: config/fuzzel
    dst: ~/.config/fuzzel
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_bat:
    src: config/bat
    dst: ~/.config/bat
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  d_fish:
    src: config/fish
    dst: ~/.config/fish
    chmod: '700'
  d_joshuto:
    src: config/joshuto
    dst: ~/.config/joshuto
  d_fontconfig:
    src: config/fontconfig
    dst: ~/.config/fontconfig
  d_hypr:
    src: config/hypr
    dst: ~/.config/hypr
  f_electron-flags.conf:
    src: config/electron-flags.conf
    dst: ~/.config/electron-flags.conf
  d_scripts:
    src: scripts
    dst: ~/.scripts
  d_applications:
    src: local/share/applications
    dst: ~/.local/share/applications
  f_mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
  d_x11:
    src: config/X11
    dst: ~/.config/X11
profiles:
  timber-desktop:
    dotfiles:
    - d_xsettingsd
    - d_fuzzel
    - d_kitty
    - d_bat
    - d_dunst
    - d_waybar
    - d_fish
    - d_joshuto
    - d_fontconfig
    - d_hypr
  timber-laptop:
    dotfiles:
    - d_xsettingsd
    - d_fuzzel
    - d_kitty
    - d_bat
    - d_dunst
    - d_waybar
    - d_fish
    - d_joshuto
    - d_fontconfig
    - d_hypr
    - f_electron-flags.conf
    - d_scripts
    - d_applications
    - f_mimeapps.list
    - d_x11
