config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_xsettingsd:
    src: config/xsettingsd
    dst: ~/.config/xsettingsd
  d_fuzzel:
    src: config/fuzzel
    dst: ~/.config/fuzzel
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_bat:
    src: config/bat
    dst: ~/.config/bat
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  d_fish:
    src: config/fish
    dst: ~/.config/fish
    chmod: '700'
  d_joshuto:
    src: config/joshuto
    dst: ~/.config/joshuto
  d_fontconfig:
    src: config/fontconfig
    dst: ~/.config/fontconfig
  d_hypr:
    src: config/hypr
    dst: ~/.config/hypr
  f_electron-flags.conf:
    src: config/electron-flags.conf
    dst: ~/.config/electron-flags.conf
  d_scripts:
    src: scripts
    dst: ~/.scripts
  d_applications:
    src: local/share/applications
    dst: ~/.local/share/applications
  f_mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
    chmod: '600'
  d_x11:
    src: config/x11
    dst: ~/.config/x11
  d_kvantum:
    src: config/Kvantum
    dst: ~/.config/Kvantum
  d_qt5ct:
    src: config/qt5ct
    dst: ~/.config/qt5ct
  d_qt6ct:
    src: config/qt6ct
    dst: ~/.config/qt6ct
  d_zathura:
    src: config/zathura
    dst: ~/.config/zathura
  d_light-mode.d:
    src: local/share/light-mode.d
    dst: ~/.local/share/light-mode.d
  d_dark-mode.d:
    src: local/share/dark-mode.d
    dst: ~/.local/share/dark-mode.d
  d_darkman:
    src: config/darkman
    dst: ~/.config/darkman
  d_ags:
    src: config/ags
    dst: ~/.config/ags
  d_xdg-desktop-portal:
    src: config/xdg-desktop-portal
    dst: ~/.config/xdg-desktop-portal
  f_electron25-flags.conf:
    src: config/electron25-flags.conf
    dst: ~/.config/electron25-flags.conf
  d_nvim:
    src: config/nvim/lua/custom
    dst: ~/.config/nvim/lua/custom
profiles:
  timber-desktop:
    dotfiles:
    - d_xsettingsd
    - d_fuzzel
    - d_kitty
    - d_bat
    - d_fish
    - d_joshuto
    - d_fontconfig
    - d_hypr
    - d_scripts
    - d_applications
    - f_mimeapps.list
    - d_x11
    - d_kvantum
    - d_qt5ct
    - d_qt6ct
    - d_zathura
    - d_light-mode.d
    - d_dark-mode.d
    - d_darkman
    - d_ags
    - d_xdg-desktop-portal
    - f_electron25-flags.conf
    - d_nvim
  timber-laptop:
    dotfiles:
    - d_xsettingsd
    - d_fuzzel
    - d_kitty
    - d_bat
    - d_fish
    - d_joshuto
    - d_fontconfig
    - d_hypr
    - d_scripts
    - d_applications
    - f_mimeapps.list
    - d_x11
    - d_kvantum
    - d_qt5ct
    - d_qt6ct
    - d_zathura
    - d_light-mode.d
    - d_dark-mode.d
    - d_darkman
    - d_ags
    - d_xdg-desktop-portal
    - f_electron25-flags.conf
    - d_nvim
